#!/usr/bin/env bash
sudo apt-get -y update
# installing nginx server
sudo apt-get -y install nginx
#adding content to the main page
sudo echo "Holberton School" > /usr/share/nginx/html/index.html
sudo chmod 777 /usr/share/nginx/html/index.html
# adding redirection to page 301
sudo sed -i "38i\ \tlocation /redirect_me {\n\t return 301;\n}" /etc/nginx/sites-enabled/default
# creating 404 page not found
sudo touch /usr/share/nginx/html/404.html
sudo chmod 777 /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
x="#error_page 404"
y="error_page 404"
#redirecting to 404.html for page not found
sudo sed -i "s/$x/$y/" /etc/nginx/sites-enabled/default
# adding HTTP header
sudo sed -i "11i\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/nginx.conf
# restarting nginx
sudo service nginx start
