#!/usr/bin/env bash
# This script checks if a network device are available on a network

if [ "$#" -eq 0 ];
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
else
    ping -c 5 "$1"
fi
