#!/usr/bin/env bash
# script changes ports in nginx so it could listen on port 80
sudo sed -i 's/8080 default_server/80 default_server/' /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart
pkill nginx
