#!/usr/bin/env bash
# This script prints Holberton School to stdout 10 times and prints Hi on the 9th iteration

index=0
while [ $index -lt 10 ]
do
if [ $index -eq 9 ]
then echo "Hi"
fi
    echo "Holberton School"
    ((index++))
done
