#!/usr/bin/env bash
# This script prints numbers from 1-20 printing special phrases at 4th, 9th and 17th iteration

index=1
while [ $index -le 20 ]
do
    case $index in
	4)
	    echo $index
	    echo "bad luck from China"
	    ;;
	9)
	    echo $index
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo $index
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $index
esac
((index++))
done  
