#!/usr/bin/env bash
# This script gives information about holbertonschool file
filename="holbertonschool"
if [ -e $filename ]
then
    echo "holbertonschool file exists"
else
    echo "holbertonschool file does not exist"
    exit
fi
    if [ -s $filename ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    if [ -f $filename ]
    then
	echo "holbertonschool file is a regular file"
    fi
fi

