#!/usr/bin/env bash
## Script installs nginx and returns a pages with string "Holberton School"
sudo apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo service nginx restart
