#!/usr/bin/env bash
##Configure your Nginx server so that /redirect_me is redirecting to 301 Moved Permanently
sudo apt-get -y install nginx
sudo echo "Holberton School" > /usr/share/nginx/html/index.html
sudo sed -i "38i\ \tlocation /redirect_me {\n\t return 301;\n}" /etc/nginx/sites-enabled/default
sudo service nginx restart
