#!/usr/bin/env bash
##Configure your Nginx server so that /redirect_me is redirecting to 404 Page not found
sudo apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo sed -i "38i\ \tlocation /redirect_me {\n\t return 301;\n}" /etc/nginx/sites-enabled/default
sudo touch /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
x="#error_page404"
y="error_page404"
sudo sed -i "s/x /y/" /etc/nginx/sites-enabled/default
sudo service nginx restart
