#!/usr/bin/env bash
# script to run nginx as an ngnix user
pkill apache2
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server;/8080 default server;/" /etc/nginx/sites-available/default
sudo -u "nginx" service nginx restart
