#!/usr/bin/env bash
# script to run nginx as an ngnix user
pkill apache2
chmod 777 /etc/nginx/nginx.conf
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server;/8080 default_server;/" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
