#!/usr/bin/env bash
# script to run nginx as an ngnix user
chmod 755 /etc/nginx/nginx.conf
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
